export const shadowRaiseDealRegistryAbi = [
  {
    type: "function",
    name: "createDeal",
    stateMutability: "nonpayable",
    inputs: [
      { name: "companyName", type: "string" },
      { name: "sector", type: "string" },
      { name: "fundingTarget", type: "uint256" },
      { name: "publicMetadataURI", type: "string" },
      { name: "publicRiskScore", type: "uint256" },
      { name: "publicRiskLevel", type: "string" },
      { name: "publicConfidenceScore", type: "uint256" },
      { name: "revenueBand", type: "string" },
      { name: "burnRiskBand", type: "string" },
      { name: "monthlyRevenue", type: "bytes32" },
      { name: "monthlyRevenueProof", type: "bytes" },
      { name: "monthlyBurn", type: "bytes32" },
      { name: "monthlyBurnProof", type: "bytes" },
      { name: "runwayMonths", type: "bytes32" },
      { name: "runwayMonthsProof", type: "bytes" },
      { name: "grossMargin", type: "bytes32" },
      { name: "grossMarginProof", type: "bytes" },
      { name: "customerCount", type: "bytes32" },
      { name: "customerCountProof", type: "bytes" },
    ],
    outputs: [{ name: "dealId", type: "uint256" }],
  },
  {
    type: "function",
    name: "getPublicDeal",
    stateMutability: "view",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "founder", type: "address" },
          { name: "companyName", type: "string" },
          { name: "sector", type: "string" },
          { name: "fundingTarget", type: "uint256" },
          { name: "publicMetadataURI", type: "string" },
          { name: "publicRiskScore", type: "uint256" },
          { name: "publicRiskLevel", type: "string" },
          { name: "publicConfidenceScore", type: "uint256" },
          { name: "revenueBand", type: "string" },
          { name: "burnRiskBand", type: "string" },
          { name: "active", type: "bool" },
          { name: "createdAt", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getDealCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getFounderDealIds",
    stateMutability: "view",
    inputs: [{ name: "founder", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "investConfidentially",
    stateMutability: "nonpayable",
    inputs: [
      { name: "dealId", type: "uint256" },
      { name: "encryptedAmount", type: "bytes32" },
      { name: "encryptedAmountProof", type: "bytes" },
    ],
    outputs: [{ name: "investmentId", type: "uint256" }],
  },
  {
    type: "function",
    name: "getInvestmentIntent",
    stateMutability: "view",
    inputs: [{ name: "investmentId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "dealId", type: "uint256" },
          { name: "investor", type: "address" },
          { name: "encryptedAmount", type: "bytes32" },
          { name: "createdAt", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getInvestorInvestmentIds",
    stateMutability: "view",
    inputs: [{ name: "investor", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
] as const;
